#!/usr/bin/env bash
set -euo pipefail

export SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd ${SUPPORT_FIRECLOUD_DIR}

# Resetting the support_firecloud directory
# if the git repo is on master and only on master.
# A development branch will therefore not be reset.
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
if [ "${BRANCH_NAME}" = "master" ]
then
    git reset
    git stash --all
    git checkout master
    git fetch
    git reset --hard origin/master
    git clean -xdf .
fi

# Bootstrap OS
OS=$(uname | tr "[A-Z]" "[a-z]")

# Check sudo permissions if using sudo.
if [ "${SF_USE_SUDO:-true}" = "true" ]
then
    echo "Enter your sudo password for bootstrap."
    sudo true
    if [ "$?" != "0" ]
    then
        >&2 echo "[ERROR] You need local admin rights to properly bootstrap." \
            "If you don't have local admin rights, try contacting the IT department."
        exit 1
    fi
fi

# Execute the os specific boostrap process.
${SUPPORT_FIRECLOUD_DIR}/ci/${OS}/bootstrap

# Check if running an old bash and offer to upgrade users login shell.
if [ "${SHELL:-}" = "/bin/bash" ]
then
    ${SUPPORT_FIRECLOUD_DIR}/bin/use-homebrew-bash
fi

# User feedback
echo
echo "Append 'source \"~/${SUPPORT_FIRECLOUD_DIR#${HOME}/}/sh/dev.inc.sh\"'"
echo "to your '~/.bashrc' or '~/.zshrc' or similar."
echo
echo "Restart your shell, and you're good to go."
