#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

if [[ "${EUID}" != "0" ]]; then
    # Restart this shell script as root.
    ${SUDO} ${BASH_SOURCE[0]}
    exit 0
fi

function apt_update() {
    apt-get update -y --fix-missing 2>&1 || {
        # try to handle "Hash Sum mismatch" error
        apt-get clean
        rm -rf /var/lib/apt/lists/*
        apt-get update -y --fix-missing
    }
}

function apt_install() {
    while read -u3 DPKG; do
        [[ -n "${DPKG}" ]] || continue

        echo_do "aptitude: Installing ${DPKG}..."
        apt-get install -y "${DPKG}"
        echo_done
    done 3< <(echo "$@")
}

if [[ "${FORCE_GIT_PPA:-}" = "true" ]]; then
    echo_do "aptitude: Adding git ppa"
    rm -rf /var/lib/apt/lists/*
    apt_install "software-properties-common"
    apt-add-repository -y ppa:git-core/ppa
    echo_done
fi

echo_do "aptitude: Updating..."
    apt_update
echo_done

if [[ "${FORCE_LOCALES:-}" = "true" ]]; then
    apt_install locales
    locale-gen en_US en_US.UTF-8
    dpkg-reconfigure --frontend=noninteractive locales
    echo locales: regenerated and reconfigured locales...
fi

echo_info locales: LANG=$LANG

echo_do "aptitude: Installing basic packages..."
DPKGS="$(cat <<-EOF
bash
bsdmainutils
build-essential
curl
file
git
groff
python-minimal
rsync
uuid-runtime
zlib1g-dev
EOF
)"
apt_install "${DPKGS}"
echo_done

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done
