#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done

brew_install_linux_nosudo() {
    if [[ -n "${BREW_FORMULAE:-}" ]]; then
        echo_info "brew: Detected predefined packages ${BREW_FORMULAE}"
        echo_skip "brew: Installing basic packages..."
        echo_skip "brew: Installing AWS packages..."
        return 0
    fi

    source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-basic.inc.sh
    source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-aws.inc.sh
}

source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-bootstrap.inc.sh
brew_install_linux_nosudo
brew_list

source ${SUPPORT_FIRECLOUD_DIR}/ci/maybe-npm.inc.sh

echo_do "Printenv..."
printenv
echo_done
