#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

source ${SUPPORT_FIRECLOUD_DIR}/ci/choco-bootstrap.inc.sh
choco_brewfile_inc_sh
choco_list

[[ "${CI:-}" != "true" ]] || {
    echo_do "Printenv..."
    printenv
    echo_done
}
